name: mf6adj
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - filelock
  - scipy>=1.7.0
  - numpy>=2.0
  - matplotlib>=3.5.0
  - pandas>=2.0.0
  - jupyter
  - notebook
  - jupyterlab
  - pytest>=9.0.2
  - pytest-cov
  - pytest-xdist
  - nbmake
  - shapely
  - h5py>=3.0.0
  - flopy>=3.10.0
  - modflowapi>=0.2.0
  - modflow6
  - pyemu>=1.4.0
  - geopandas>=1.0.0
  - modflow-devtools>=1.9.1
  - boltons
  - tomli-w
  - pyshp
  - ruff
  - codespell>=2.2.2
